{% set name = "compas_mobile_robot_reloc" %}
{% set version = "1.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6071b9a8dc0fcc75e77b947e87b5ce41c52dfa5c09e1751f99de35b76967dcf1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - pep517
    - pip
    - python >=3.7
    - setuptools-scm
    - wheel
  run:
    - compas >=0.17.2,<2.0
    - python >=3.7

test:
  imports:
    - compas_mobile_robot_reloc
    - compas_mobile_robot_reloc.utils
    - compas_mobile_robot_reloc.xforms
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - pytest -vv tests

about:
  home: https://gramaziokohler.github.io/compas_mobile_robot_reloc
  summary: Robot localization using external measuring device (total station).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tetov
